CREATE TABLE roles (
  id BIGINT UNSIGNED NOT NULL AUTOINCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  role VARCHAR(64) NOT NULL,
  assotiated_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  assotiated_str VARCHAR(128) NOT NULL DEFAULT '',
  granted_by BIGINT UNSIGNED NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET 0,
  CONSTRAINT unique_role_user_id UNIQUE (user_id, role)
);

