CREATE TABLE roles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  role VARCHAR(64) NOT NULL,
  assotiated_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  assotiated_str VARCHAR(128) NOT NULL DEFAULT '',
  granted_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET 0,
  CONSTRAINT unique_role_user_id UNIQUE (user_id, role)
);

CREATE TABLE cert_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  requested_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  cert_type INT UNSIGNED NOT NULL DEFAULT 0,

  name VARCHAR(128) NOT NULL DEFAULT '',
  lastname VARCHAR(128) NOT NULL DEFAULT '',
  middlename VARCHAR(128) NOT NULL DEFAULT '',
  iin CHAR(32) NOT NULL DEFAULT '',
  start_date DATE NOT NULL,
  birth_date DATE NOT NULL,
  study_form_id INT NOT NULL DEFAULT 0,
  specialization_code VARCHAR(16) NOT NULL DEFAULT '',
  grant_type INT NOT NULL DEFAULT 0,
  course_count INT NOT NULL DEFAULT 0,
  course_number INT NOT NULL DEFAULT 0,
  study_form_name_ru VARCHAR(128) NOT NULL DEFAULT '',
  study_form_name_kz VARCHAR(128) NOT NULL DEFAULT '',
  study_form_name_en VARCHAR(128) NOT NULL DEFAULT '',
  specialization_name_ru VARCHAR(256) NOT NULL DEFAULT '',
  specialization_name_kz VARCHAR(256) NOT NULL DEFAULT '',
  specialization_name_en VARCHAR(256) NOT NULL DEFAULT '',
  cafedra_ru VARCHAR(256) NOT NULL DEFAULT '',
  cafedra_kz VARCHAR(256) NOT NULL DEFAULT '',
  cafedra_en VARCHAR(256) NOT NULL DEFAULT '',
  dekanat_ru VARCHAR(256) NOT NULL DEFAULT '',
  dekanat_kz VARCHAR(256) NOT NULL DEFAULT '',
  dekanat_en VARCHAR(256) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET DEFAULT
);